// Static game content: classes, skills, items, enemies, and zones.

import type { ClassId, Enemy, Item, ItemId, Skill, Stats, Zone } from "./types";

export const CLASSES: Record<
  ClassId,
  { id: ClassId; name: string; sprite: string; blurb: string; base: Stats; growth: Stats }
> = {
  warrior: {
    id: "warrior",
    name: "Warrior",
    sprite: "🛡️",
    blurb: "Tough and hard-hitting. High HP and defense, low magic.",
    base: { maxHp: 42, maxMp: 8, atk: 9, def: 6, mag: 2, spd: 4 },
    growth: { maxHp: 9, maxMp: 2, atk: 3, def: 2, mag: 1, spd: 1 },
  },
  mage: {
    id: "mage",
    name: "Mage",
    sprite: "🔮",
    blurb: "Fragile but devastating. Spells scale hard with magic.",
    base: { maxHp: 26, maxMp: 22, atk: 4, def: 3, mag: 9, spd: 5 },
    growth: { maxHp: 5, maxMp: 6, atk: 1, def: 1, mag: 3, spd: 1 },
  },
  rogue: {
    id: "rogue",
    name: "Rogue",
    sprite: "🗡️",
    blurb: "Fast and lucky. High speed means more crits and clean escapes.",
    base: { maxHp: 32, maxMp: 14, atk: 7, def: 4, mag: 5, spd: 9 },
    growth: { maxHp: 7, maxMp: 3, atk: 2, def: 1, mag: 2, spd: 3 },
  },
};

export const SKILLS: Skill[] = [
  {
    id: "power_strike",
    name: "Power Strike",
    kind: "attack",
    mpCost: 4,
    power: 1.6,
    desc: "A heavy blow scaling with Attack.",
    learnAtLevel: 2,
    classes: ["warrior", "rogue"],
  },
  {
    id: "guard_up",
    name: "Iron Guard",
    kind: "buff",
    mpCost: 3,
    power: 0,
    buff: { stat: "def", amount: 6, turns: 3 },
    desc: "Raise Defense for 3 turns.",
    learnAtLevel: 3,
    classes: ["warrior"],
  },
  {
    id: "firebolt",
    name: "Firebolt",
    kind: "attack",
    mpCost: 5,
    power: 1.9,
    desc: "Hurl a bolt of flame. Scales with Magic.",
    learnAtLevel: 2,
    classes: ["mage", "rogue"],
  },
  {
    id: "frost_nova",
    name: "Frost Nova",
    kind: "attack",
    mpCost: 9,
    power: 2.6,
    desc: "A burst of freezing power. Scales with Magic.",
    learnAtLevel: 5,
    classes: ["mage"],
  },
  {
    id: "mend",
    name: "Mend",
    kind: "heal",
    mpCost: 6,
    power: 2.2,
    desc: "Restore HP based on Magic.",
    learnAtLevel: 3,
    classes: ["mage", "rogue"],
  },
  {
    id: "focus",
    name: "Focus",
    kind: "buff",
    mpCost: 4,
    power: 0,
    buff: { stat: "atk", amount: 5, turns: 3 },
    desc: "Sharpen your strikes for 3 turns.",
    learnAtLevel: 4,
    classes: ["rogue", "warrior"],
  },
];

export const ITEMS: Record<ItemId, Item> = {
  potion: {
    id: "potion",
    name: "Potion",
    price: 15,
    desc: "Restore 30 HP.",
    effect: { hp: 30 },
  },
  hi_potion: {
    id: "hi_potion",
    name: "Hi-Potion",
    price: 45,
    desc: "Restore 80 HP.",
    effect: { hp: 80 },
  },
  ether: {
    id: "ether",
    name: "Ether",
    price: 40,
    desc: "Restore 25 MP.",
    effect: { mp: 25 },
  },
  phoenix: {
    id: "phoenix",
    name: "Phoenix Down",
    price: 90,
    desc: "Revive with half HP if you fall in battle.",
    effect: { revive: true },
  },
};

export const SHOP_STOCK: ItemId[] = ["potion", "hi_potion", "ether", "phoenix"];

// Enemy templates. Actual stats are scaled by zone in engine.spawnEnemy.
type EnemyTemplate = Omit<Enemy, "hp" | "statuses"> & { hpFull: number };

export const ENEMIES: Record<string, EnemyTemplate> = {
  slime: {
    id: "slime",
    name: "Green Slime",
    sprite: "🟢",
    maxHp: 18,
    hpFull: 18,
    atk: 5,
    def: 2,
    mag: 0,
    spd: 3,
    xp: 6,
    gold: 5,
  },
  bat: {
    id: "bat",
    name: "Cave Bat",
    sprite: "🦇",
    maxHp: 14,
    hpFull: 14,
    atk: 6,
    def: 1,
    mag: 0,
    spd: 8,
    xp: 7,
    gold: 6,
  },
  wolf: {
    id: "wolf",
    name: "Dire Wolf",
    sprite: "🐺",
    maxHp: 30,
    hpFull: 30,
    atk: 9,
    def: 3,
    mag: 0,
    spd: 7,
    xp: 12,
    gold: 10,
  },
  goblin: {
    id: "goblin",
    name: "Goblin Raider",
    sprite: "👺",
    maxHp: 34,
    hpFull: 34,
    atk: 10,
    def: 4,
    mag: 2,
    spd: 6,
    xp: 14,
    gold: 14,
  },
  wisp: {
    id: "wisp",
    name: "Ember Wisp",
    sprite: "🔥",
    maxHp: 26,
    hpFull: 26,
    atk: 6,
    def: 2,
    mag: 9,
    spd: 9,
    xp: 16,
    gold: 12,
  },
  golem: {
    id: "golem",
    name: "Stone Golem",
    sprite: "🗿",
    maxHp: 60,
    hpFull: 60,
    atk: 12,
    def: 10,
    mag: 0,
    spd: 2,
    xp: 24,
    gold: 22,
  },
  wraith: {
    id: "wraith",
    name: "Frost Wraith",
    sprite: "👻",
    maxHp: 48,
    hpFull: 48,
    atk: 11,
    def: 5,
    mag: 12,
    spd: 10,
    xp: 28,
    gold: 26,
  },
  // Bosses
  boss_grumble: {
    id: "boss_grumble",
    name: "Grumble, Slime King",
    sprite: "👑",
    maxHp: 90,
    hpFull: 90,
    atk: 11,
    def: 6,
    mag: 3,
    spd: 5,
    xp: 60,
    gold: 80,
    isBoss: true,
  },
  boss_fang: {
    id: "boss_fang",
    name: "Fang, Alpha of the Pack",
    sprite: "🐲",
    maxHp: 150,
    hpFull: 150,
    atk: 16,
    def: 8,
    mag: 6,
    spd: 12,
    xp: 120,
    gold: 160,
    isBoss: true,
  },
  boss_pyre: {
    id: "boss_pyre",
    name: "Pyraxis the Everburning",
    sprite: "🐉",
    maxHp: 240,
    hpFull: 240,
    atk: 20,
    def: 11,
    mag: 18,
    spd: 11,
    xp: 240,
    gold: 320,
    isBoss: true,
  },
};

export const ZONES: Zone[] = [
  {
    id: "meadow",
    name: "Whispering Meadow",
    blurb: "Rolling grass and slow, squishy foes. A gentle start.",
    minLevel: 1,
    enemyPool: ["slime", "bat"],
    boss: "boss_grumble",
    bg: "from-emerald-900 via-emerald-800 to-teal-900",
  },
  {
    id: "hollow",
    name: "Ashen Hollow",
    blurb: "Scorched woods prowled by beasts and burning wisps.",
    minLevel: 4,
    enemyPool: ["wolf", "goblin", "wisp"],
    boss: "boss_fang",
    bg: "from-orange-950 via-red-950 to-amber-900",
  },
  {
    id: "spire",
    name: "Frostspire Peak",
    blurb: "A frozen summit guarded by golems, wraiths, and worse.",
    minLevel: 8,
    enemyPool: ["golem", "wraith", "wisp"],
    boss: "boss_pyre",
    bg: "from-sky-950 via-indigo-950 to-slate-900",
  },
];
